---
_repo_version: '{{ (_target_kubeadm_version|regex_findall("(?:\d+)"))[0:2]|join(".") }}'
kubernetes_repository: >-
  {%- if _repo_version is version("1.24", ">=") -%}
    {{ kubernetes_new_repository }}
  {%- else -%}
    {{ kubernetes_old_repository }}
  {%- endif -%}

kubernetes_new_repository:
  gpg_url: 'https://pkgs.k8s.io/core:/stable:/v{{ _repo_version }}/deb/Release.key'
  repo_url: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ _repo_version }}/deb/ /'

kubernetes_old_repository:
  gpg_url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
  repo_url: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://apt.kubernetes.io/ kubernetes-xenial main'

repository_dependencies:
  - apt-transport-https
  - ca-certificates
  - gnupg

kubeadm_packages:
  - kubeadm
  - kubectl  # As a dependency but without version specification
  - kubernetes-cni

node_packages:
  - kubelet
  - kubernetes-cni

control_plane_packages:
  - kubectl

packages_force_version:
  kubernetes-cni:

python2_openssl: python-openssl
python3_openssl: python3-openssl
