---
- name: 'Plan upgrade'
  command: kubeadm upgrade plan {{ kubeadm_version.version.split( '-' )|first }}
  register: plan_upgrade

- debug:
    msg: >-
      {{ dict(stderr=plan_upgrade.stderr_lines,
              stdout=plan_upgrade.stdout_lines) }}

- name: 'Apply upgrade'
  command: kubeadm upgrade apply {{ kubeadm_version.version.split( '-' )|first }} -y
  register: apply_upgrade

- debug:
    msg: >-
      {{ dict(stderr=apply_upgrade.stderr_lines,
              stdout=apply_upgrade.stdout_lines) }}
