---
- name: 'install docker-python binding'
  package:
    name:
      - docker-compose
      - >
        {%- if ansible_python.version.major > 2 -%}
          {{ python3_docker }}
        {%- else -%}
          {{ python2_docker }}
        {%- endif -%}
    state: present
  register: compose_installed

- name: 'create stack directory'
  file:
    dest: '{{ apiserver_proxy_stack_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: 'Install apiserver-proxy'
  copy:
    src: docker-compose.yaml
    dest: '{{ apiserver_proxy_stack_dir }}/docker-compose.yaml'
    owner: root
    group: root
    mode: 0600

- name: 'Template environement variable'
  template:
    src: apiserver-proxy-endpoints.env.j2
    dest: '{{ apiserver_proxy_stack_dir }}/apiserver-proxy-endpoints.env'
    owner: root
    group: root
    mode: 0600

- name: 'Start compose stack'
  docker_compose:
    project_src: '{{ apiserver_proxy_stack_dir }}'
    state: present
  when: >-
    not(compose_installed is changed and ansible_check_mode)
  vars:
    ansible_python_interpreter: >-
      {%- if ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04" -%}
        /usr/bin/python2
      {%- else -%}
        {{ ansible_python.executable }}
      {%- endif -%}
