---
- name: 'Include OS specific variables'
  include_vars: '{{ item }}'
  with_fileglob:
    - 'vars/os_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml'
    - 'vars/os_{{ ansible_distribution }}.yml'
    - 'vars/os_{{ ansible_os_family }}.yml'

- name: 'Include Docker tasks'
  include_tasks: 'docker.yml'
  when: apiserver_proxy_use_docker|bool

- name: 'Include package tasks'
  include_tasks: 'package.yml'
  when: not apiserver_proxy_use_docker|bool

- name: 'export vars'
  set_fact:
    control_plane_endpoint: "127.0.0.1:{{ apiserver_proxy_port }}"
