---
stages:
  - pre-build
  - lint
  - test

include: .gitlab-ci/build-tooling-image.yml

yamllint:
  stage: lint
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  script:
    - tox -e tools -- yamllint .

ansible-lint:
  stage: lint
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  script:
    - tox -e tools -- ansible-lint

.openstack-test:
  stage: test
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  variables:
    TF_VAR_stem: "${CI_JOB_ID}"
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.enix.io".insteadOf "ssh://git@gitlab.enix.io"
    - ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/id_rsa
    - tox -e tests --notest

openstack-tests-everything:
  extends: .openstack-test
  script:
    - tox -e tests -- -s -k "not upgrade"

openstack-tests-upgrade:
  extends: .openstack-test
  script:
    - tox -e tests -- -s -k "upgrade"
