---
stages:
  - pre-build
  - lint
  - test
  - test-2
  - test-3
  - test-4

variables:
  FIRST_VERSION: '1.19'
  LAST_VERSION: '1.22'

include: .gitlab-ci/build-tooling-image.yml

yamllint:
  stage: lint
  image: registry.gitlab.com/enix.io/ansible-kubeadm/tooling:latest
  script:
    - tox -e tools -- yamllint .

ansible-lint:
  stage: lint
  image: registry.gitlab.com/enix.io/ansible-kubeadm/tooling:latest
  script:
    - tox -e tools -- ansible-lint

.openstack-test:
  stage: test
  image: registry.gitlab.com/enix.io/ansible-kubeadm/tooling:latest
  services:
    - name: docker:23-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    TF_VAR_stem: "${CI_JOB_ID}"
  before_script:
    - git config --global url."https://${GITLAB_ENIX_TOKEN_NAME:-'gitlab-ci-token'}:${GITLAB_ENIX_TOKEN:-${CI_JOB_TOKEN}}@gitlab.enix.io".insteadOf "ssh://git@gitlab.enix.io"
    - "[ ! -f tests/ssh/id_rsa ] && mkdir -p tests/ssh/ && ssh-keygen -t rsa -b 2048 -N '' -f tests/ssh/id_rsa"
    - ln -s ${CI_PROJECT_DIR}/tests/ssh ~/.ssh
    - tox -e tests --notest

openstack-tests-ansible-3:
  extends: .openstack-test
  script:
    - poetry install
    - poetry run pytest -s
