---
stages:
  - pre-build
  - lint
  - test

include: .gitlab-ci/build-tooling-image.yml

.external-git: &external-git
  - git config --global url."https://gitlab.enix.io".insteadOf "ssh://git@gitlab.enix.io"
  - git config --global credential.helper $(readlink -f tests/git-creds.sh)

yamllint:
  stage: lint
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  script:
    - tox -e tools -- yamllint .

ansible-lint:
  stage: lint
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  before_script: *external-git
  script:
    - tox -e tools -- ansible-lint

openstack-tests:
  stage: test
  image: docker-registry.enix.io/kubernetes/ansible-kubeadm/tooling:latest
  variables:
    TF_VAR_stem: "${CI_JOB_ID}"
  before_script:
    - *external-git
    - ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/id_rsa
    - tox -e tests --notest
  script:
    - tox -e tests -- -s
