---
services:
  tests:
    build: .
    image: ${RUN_TEST_IMAGE:-ghcr.io/chtrifork/ansible-kubeadm:latest}
    working_dir: "${PWD}"
    entrypoint: [
      "/bin/bash", "-c",
      "poetry install"
    ]
    #command: ["-x"]
    command: ["/bin/bash"]
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}:${PWD}
        - /tmp:/tmp
        - ${_SSH_AUTH_SOCK:-${SSH_AUTH_SOCK:-/run}}:${_SSH_AUTH_SOCK:-${SSH_AUTH_SOCK:-/run}}
        - ${SSH_KEY:-${HOME}}:${SSH_KEY_MOUNT:-${SSH_KEY:-${HOME}}}
    environment:
        POETRY_CACHE_DIR: "${POETRY_CACHE_DIR:-/tmp}"
        POETRY_VIRTUALENVS_PATH: "${POETRY_VIRTUALENVS_PATH:-/tmp}"
        SSH_AUTH_SOCK: "${_SSH_AUTH_SOCK:-${SSH_AUTH_SOCK:-/run}}"