---
- name: "Create pinning files"
  copy:
    dest: /etc/apt/preferences.d/{{ item.pkg }}
    content: |-
      package: {{ item.pkg }}
      Pin: version {{ item.version }}
      Pin-Priority: 1001
  loop: "{{ kube_package_dict|dict2items('pkg', 'version')|selectattr('version') }}"

- name: "Remove pinning files"
  file:
    dest: /etc/apt/preferences.d/{{ item.pkg }}
    state: absent
  loop: "{{ kube_package_dict|dict2items('pkg', 'version')|rejectattr('version') }}"

- name: 'Unhold package before upgrade'
  dpkg_selections:
    selection: 'install'
    name: '{{ item }}'
  loop: "{{ kube_package_dict.keys() }}"

- name: 'Install kubernetes packages'
  apt:
    name: "{{ kube_package_dict.keys() }}"
    state: "latest"
