---
- name: 'Update kubeadm config'
  run_once: true
  delegate_to: '{{ cp_node }}'
  block:
    - name: 'set some facts'
      set_fact:
        kubeadm_config_yaml: '{{ kubeadm_config_yaml }}'

    - name: 'write kubeadm config if modification needed'
      template:
        src: 'kubeadm_config.yaml.j2'
        dest: '{{ kubeadm_config_yaml }}'
        owner: root
        group: root
        mode: 0600
      register: _kubeadm_configs_write
      when: >-
        _cluster_config_diff.diff_lines|length > 0
        or _kubelet_config_diff.diff_lines|length > 0
        or _kubeproxy_config_diff.diff_lines|length > 0
        or groups.cp_running|default([])|length == 0

    - name: 'reupload KUBEADM/KUBELET config if cluster running'
      command: kubeadm init phase upload-config all --config {{ kubeadm_config_yaml }}
      environment:
        KUBECONFIG: '/etc/kubernetes/admin.conf'
      when:
        - _kubeadm_configs_write is changed
        - _cluster_config_diff.diff_lines|length > 0
          or _kubelet_config_diff.diff_lines|length > 0
        - groups.cp_running|default([])|length > 0

    - name: 'reupload KUBEPROXY config if cluster running'
      command: kubeadm init phase addon kube-proxy --config {{ kubeadm_config_yaml }}
      environment:
        KUBECONFIG: '/etc/kubernetes/admin.conf'
      when:
        - _kubeadm_configs_write is changed
        - _kubeproxy_config_diff.diff_lines|length > 0
        - groups.cp_running|default([])|length > 0
