---
- name: 'Retrive variable from control-plane'
  set_fact:
    target_kube_version: '{{ cp_vars.target_kube_version }}'
    target_kubeadm_version: '{{ cp_vars.target_kubeadm_version }}'
  vars:
    cp_vars: '{{ hostvars[groups.kube_control_plane|first] }}'

- name: 'Get version of kubelet package'
  package_facts:

- debug:
    var: packages.kubectl

- debug:
    var: target_kubeadm_version

- name: 'Add to upgrade group if difference found'
  add_host:
    groups: nodes_upgrade
    name: '{{ item }}'
  run_once: true
  check_mode: false
  changed_when: false
  # noqa 104
  with_items: >-
    [ {%- for host in ansible_play_hosts
          if hostvars[host].packages.kubelet|default([])
             |rejectattr('version', 'eq', target_kubeadm_version)|list|length > 0 -%}
            '{{ host }}',
      {%- endfor -%} ]
