---
apiserver_proxy_apiserver_port: 6443
_apiserver_proxy_haproxy_version: '2.6.*'
force_apt_update: false
haproxy_repo_url: '{{ haproxy_upstream_repo_url }}'
haproxy_gpg_url: '{{ haproxy_upstream_gpg_url }}'

# From apiserver_docker
apiserver_proxy_stack_dir: '/etc/docker-compose/apiserver-proxy'
