---
- name: 'Pause before upgrade'
  pause:
  when: pause_before_upgrade|bool

- name: 'Apply upgrade'
  command: >-
    kubeadm upgrade node
    {% if _control_plane and enable_kubeadm_patches|bool -%}
      {% if _target_kube_version is version("1.23", "<") -%}
        {% if _target_kube_version is version("1.22", ">=") -%}
        --patches
        {%- else -%}
        --experimental-patches
        {%- endif %}
        {{ kubeadm_patch_dir }}
      {%- endif %}
    {%- endif -%}
    {% for error in kubeadm_ignore_preflight_errors %}
    --ignore-preflight-errors={{ error }}
    {% endfor %}
  register: upgrade_node
  notify:
    - Restart kubelet

- name: 'Display result of "kubeadm upgrade node"'
  debug:
    msg: >-
      {{ dict(stderr=upgrade_node.stderr_lines,
              stdout=upgrade_node.stdout_lines) }}
