---
- name: 'Apply upgrade'
  command: >-
    kubeadm upgrade node
    {% if _control_plane and enable_kubeadm_patches|bool -%}
      {% if _target_kube_version is version("1.23", "<") -%}
        {% if _target_kube_version is version("1.22", ">=") -%}
        --patches
        {%- else -%}
        --experimental-patches
        {%- endif %}
        {{ kubeadm_patch_dir }}
      {%- endif %}
    {%- endif -%}
  register: upgrade_node

- name: 'Display result of "kubeadm upgrade node"'
  debug:
    msg: >-
      {{ dict(stderr=upgrade_node.stderr_lines,
              stdout=upgrade_node.stdout_lines) }}
