---
default_kubeadm_config:
  apiVersion: >-
    {%- if _target_kube_version is version("1.22", ">=") -%}
      kubeadm.k8s.io/v1beta3
    {%- else -%}
      kubeadm.k8s.io/v1beta2
    {%- endif -%}
  kind: ClusterConfiguration

default_kubelet_config:
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration

default_kubeproxy_config:
  apiVersion: kubeproxy.config.k8s.io/v1alpha1
  kind: KubeProxyConfiguration
