---
- name: 'merge requested kubeadm config with existing one'
  set_fact:
    cluster_config_final: >-
      {%- if control_plane_endpoint|string|lower == 'false' -%}
         {%- set _ = cluster_config_orig.pop('controlPlaneEndpoint', false) -%}
      {%- elif control_plane_endpoint -%}
         {%- set cluster_config = cluster_config|combine({'controlPlaneEndpoint': control_plane_endpoint}) -%}
      {%- endif -%}
      {{ cluster_config_orig|combine(cluster_config) }}

- name: 'write kubeconfig if modification needed'
  copy:
    content: '{{ cluster_config_final|to_nice_yaml(indent=2) }}'
    dest: '{{ kubeadm_config_yaml }}'
  run_once: true
  delegate_to: '{{ kubeadm_host }}'
  when: >-
    cluster_config_final != cluster_config_orig
    or cp_running_hosts|length == 0

- name: 'reupload config if cluster running'
  command: kubeadm init phase upload-config kubeadm --config {{ kubeadm_config_yaml }}
  run_once: true
  delegate_to: '{{ kubeadm_host }}'
  when:
    - cluster_config_final != cluster_config_orig
    - cp_running_hosts|length > 0
