---
- name: 'Pause after drain'
  pause:
  when: pause_after_drain|bool

- name: 'Reboot node'
  reboot:
  when: reboot_node|bool

- name: 'Wait for node'
  wait_for_connection:
  when: reboot_node|bool

- name: 'Uncordon node'
  command: kubectl uncordon {{ ansible_nodename }}
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  retries: 4
  register: uncordon_nodes
  until: uncordon_nodes is not failed
  delegate_to: '{{ cp_node }}'
  when: drain_node|bool
