---
- hosts: kube_control_plane
  roles:
    - role: cp-preflight-check
    - role: packages
      vars:
        control_plane_pkgs: true
    - role: control-plane-init
    - role: user-kubeconfig

- hosts: kube_nodes
  roles:
    - role: nodes-preflight-check
    - role: packages
    - role: worker-plane-join
