---
- hosts: '{{ kube_cp_group|default("kube_control_plane") }}:{{ kube_worker_group|default("kube_workers") }}'
  gather_facts: false
  tags: ['always', 'plugins']
  roles:
    - role: hooks_plugins_register

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  vars:
    _control_plane: true
  roles:
    - role: find_ip

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}:{{ kube_worker_group|default("kube_workers") }}'
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['pre_apiserver_proxy']
  roles:
    - role: apiserver_haproxy
      when: apiserver_proxy_use_docker|bool in [none, false]
    - role: apiserver_docker
      when: apiserver_proxy_use_docker|bool == true
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['post_apiserver_proxy']

- hosts: 'haproxy_upgrade_group:&{{ kube_cp_group|default("kube_control_plane") }}'
  serial: '{{ upgrade_cp_serial|default(1) }}'
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['pre_proxy_upgrade_haproxy']
  roles:
    - role: apiserver_haproxy_upgrade
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['post_proxy_upgrade_haproxy']

- hosts: 'haproxy_upgrade_group:&{{ kube_worker_group|default("kube_workers") }}'
  serial: '{{ upgrade_worker_serial|default(1) }}'
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['pre_proxy_upgrade_haproxy']
  roles:
    - role: apiserver_haproxy_upgrade
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_list: ['post_proxy_upgrade_haproxy']
