---
- hosts: kube_control_plane
  roles:
    - role: preflight_check_cp

- hosts: kube_control_plane:kube_workers
  roles:
    - role: preflight_check_nodes

# This has to be overly cautious on package upgade
- hosts: cp_upgrade
  gather_facts: false
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_cp
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true

- include: 02-node-upgrade.yml

# After uprgade is done we can enforce all package version
- hosts: kube_control_plane
  roles:
    - role: packages
      vars:
        control_plane_pkgs: true
    - role: control_plane_init
    - role: join_nodes
      vars:
        control_plane: true
    - role: user_kubeconfig

- hosts: kube_workers
  roles:
    - role: packages
    - role: join_nodes
