---
- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_run
  roles:
    - role: find_ip
      vars:
        _control_plane: true
    - role: kubeadm_configs_compute
    - role: preflight_check_cp
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_preflight_cp

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}:{{ kube_worker_group|default("kube_workers") }}'
  roles:
    - role: find_ip
    - role: preflight_check_nodes
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_preflight_nodes

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  roles:
    - role: control_plane_patches
  tasks:
  - include_role:
      name: hooks_call
    vars:
      kubeadm_hook_name: post_first_tasks_cp

- hosts: cp_init
  gather_facts: false
  vars:
    _control_plane: true
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_init

  roles:
    - role: packages
    - role: init_cp
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_init

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_config_update
  roles:
    - role: bootstrap_token
    - role: kubeadm_configs_update
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_config_update

# This has to be overly cautious on package upgade
- hosts: cp_upgrade
  gather_facts: false
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_kube_upgrade
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_cp
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_kube_upgrade

# Upgrade conrol-plane nodes
- name: 'Upgrade to control plane nodes'
  hosts: '{{ kube_cp_group|default("kube_control_plane") }}:&nodes_upgrade'
  serial: '{{ upgrade_cp_serial|default(1) }}'
  gather_facts: false
  vars:
    _control_plane: true
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_cp_upgrade
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_nodes
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_cp_upgrade

# Upgrade worker nodes
- name: 'Upgrade to workers nodes'
  hosts: '{{ kube_worker_group|default("kube_workers") }}:&nodes_upgrade'
  serial: '{{ upgrade_worker_serial|default(1) }}'
  gather_facts: false
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_workers_upgrade
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_nodes
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_workers_upgrade

# Join control-plane nodes
- name: 'Join new control plane nodes'
  hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  vars:
    _control_plane: true
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_cp_join
  roles:
    - role: find_ip
    - role: packages
    - role: control_plane_patches
    - role: join_nodes
    - role: user_kubeconfig
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_cp_join

# Join worker nodes
- name: 'Join new workers nodes'
  hosts: '{{ kube_worker_group|default("kube_workers") }}'
  gather_facts: false
  pre_tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: pre_workers_join
  roles:
    - role: find_ip
    - role: packages
    - role: join_nodes
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_workers_join

- name: 'Finally executing post_run hook on all hosts'
  hosts: '{{ kube_cp_group|default("kube_control_plane") }}:{{ kube_worker_group|default("kube_workers") }}'
  gather_facts: false
  tasks:
    - include_role:
        name: hooks_call
      vars:
        kubeadm_hook_name: post_run
