- name: 'Retrive variable from control-plane'
  set_fact:
    kube_version: '{{ cp_vars.kube_version }}'
    ca_info: '{{ cp_vars.ca_info }}'
    valid_bootstrap_tokens: '{{ cp_vars.valid_bootstrap_tokens }}'
    control_plane_endpoint: '{{ cp_vars.control_plane_endpoint }}'
  vars:
    cp_vars: '{{ hostvars[groups.kube_control_plane|first] }}'
