name: run-test
on: [push]

env:
  KEEP_SERVERS_AFTER_FAIL: "false"
  OS_CLOUD: ${{ secrets.OS_CLOUD }}
  OS_DOMAIN_NAME: ${{ secrets.OS_DOMAIN_NAME }}
  TF_VAR_stem: ${{ github.sha }}

jobs:
  run-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run linting tests
        run: docker compose run shell ./scripts/lint.sh

      - name: Prepare worker
        run: |
          ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/id_rsa
          mkdir -p ~/.config/openstack
          echo "${{ secrets.OS_CLIENT_CONFIG_FILE }}" > ~/.config/openstack/clouds.yaml

      - name: Run tests
        run: docker compose run tests
