---
- name: 'Install software-properties-common'
  apt:
    name: software-properties-common

- name: 'Add the HAProxy repository'
  apt_repository:
    repo: 'ppa:vbernat/haproxy-{{ _apiserver_proxy_haproxy_version | regex_replace("^(\d+[.]\d+)[.].+", "\1") }}'
    filename: haproxy
    state: present
  register: haproxy_repo_just_added

- name: 'refresh source list'
  apt:
    update_cache: true
  when: >-
    haproxy_repo_just_added is changed
    or force_apt_update|bool
